### ISSUE TITLE
About the duplicate index in crn.py

### ISSUE THREAD

**Issue by wang422003** [enricozb/python-crn#1]
Hello,

Many thanks for the excellent work.

I just found something that confused me. There is an "i" at line 96 in "crn.py" and shortly afterward there is another "i" at line 99, which seems to be an inner iteration.  I would like to ask whether these "i"s could affect the running of this project?

Many thanks in advance.
Ralf

**Comment by enricozb** [comment]
Hi Ralf,

the code you're referring to is this section here:
```python
# Has to be iterated this way to laws is in order
for i in range(len(self.species_index)):
    sp = self.species_index[i]
    law = self.rate_law_for_species(sp)
    for i, s in self.species_index.items():
        sub = 1 if s == "nothing" else f"v[{i}]"
        law = law.subs(s, sub)
    laws.append(str(law))
```
since after the inner for loop the `i` is not used again, there is no issue in using the indexes like this.

I could have made this clearer though, thanks for bringing this up!
